import NewPlatformFlexberryWebDesignerGenerationEController from '../new-platform-flexberry-web-designer-generation-e';

var NewPlatformFlexberryWebDesignerGenerationENewController = NewPlatformFlexberryWebDesignerGenerationEController;
export default NewPlatformFlexberryWebDesignerGenerationENewController;
