---
language: node_js
node_js:
  - "6.10.3"

sudo: required

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-release

dist: trusty

addons:
  chrome: stable

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - yarn global add ember-cli@2.4.3
  - yarn global add bower
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

install:
  - yarn install --no-lockfile
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test

after_script:
  - test $EMBER_TRY_SCENARIO == "default" && test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop" || test $TRAVIS_BRANCH == "dummy-test")  && ember build --gh-pages --gh-pages-branch=$TRAVIS_BRANCH && bash scripts/deploy-to-gh-pages.sh
