import NewPlatformFlexberryWebDesignerViewEditFormController from '../new-platform-flexberry-web-designer-view-edit-form';

var NewPlatformFlexberryWebDesignerViewEditFormNewController = NewPlatformFlexberryWebDesignerViewEditFormController;
export default NewPlatformFlexberryWebDesignerViewEditFormNewController;
