import NewPlatformFlexberryWebDesignerDiagramEditFormController from '../new-platform-flexberry-web-designer-diagram-edit-form';

var NewPlatformFlexberryWebDesignerDiagramEditFormNewController = NewPlatformFlexberryWebDesignerDiagramEditFormController;
export default NewPlatformFlexberryWebDesignerDiagramEditFormNewController;
